import k4a
# region LOGGERS
LOGGER_OBJECT_DETECTOR_STARTUP = 'obj_detector_startup'
LOGGER_OBJECT_DETECTOR_MAIN = 'obj_detector_object_py'
LOGGER_OBJECT_DETECTOR_LOAD_MODEL = 'obj_detector_object_py_load_model'
LOGGER_OBJECT_DETECTOR_RUN_DETECTION = 'obj_detector_run_detection'
LOGGER_OBJECT_DETECTOR_ASYNC_RUN_DETECTION = 'obj_detector_async_run_detection'
LOGGER_OBJECT_DETECTOR_MQTT_LOOP = 'obj_detector_mqtt_loop'
LOGGER_OBJECT_DETECTOR_RUNNER = 'obj_detector_runner'
LOGGER_OBJECT_DETECTOR_ASYNC_LOOP = 'obj_detector_async_loop'
LOGGER_OBJECT_DETECTOR_ASYNC_PROCESS_MQTT = 'obj_detector_proc_mqtt'
LOGGER_OBJECT_DETECTOR_KILL_SWITCH = 'obj_detector_kill_sw'
# endregion

K4A_DEFINITIONS = {
    "K4A_IMAGE_FORMAT_COLOR_MJPG": k4a.K4A_IMAGE_FORMAT_COLOR_MJPG,
    "K4A_IMAGE_FORMAT_COLOR_BGRA32": k4a.K4A_IMAGE_FORMAT_COLOR_BGRA32,
    "K4A_IMAGE_FORMAT_COLOR_NV12": k4a.K4A_IMAGE_FORMAT_COLOR_NV12,
    "K4A_IMAGE_FORMAT_COLOR_YUY2": k4a.K4A_IMAGE_FORMAT_COLOR_YUY2,
    "K4A_IMAGE_FORMAT_CUSTOM": k4a.K4A_IMAGE_FORMAT_CUSTOM,
    "K4A_IMAGE_FORMAT_CUSTOM16": k4a.K4A_IMAGE_FORMAT_CUSTOM16,
    "K4A_IMAGE_FORMAT_CUSTOM8": k4a.K4A_IMAGE_FORMAT_CUSTOM8,
    "K4A_COLOR_RESOLUTION_720P": k4a.K4A_COLOR_RESOLUTION_720P,
    "K4A_COLOR_RESOLUTION_1080P": k4a.K4A_COLOR_RESOLUTION_1080P,
    "K4A_COLOR_RESOLUTION_1440P": k4a.K4A_COLOR_RESOLUTION_1440P,
    "K4A_COLOR_RESOLUTION_1536P": k4a.K4A_COLOR_RESOLUTION_1536P,
    "K4A_COLOR_RESOLUTION_2160P": k4a.K4A_COLOR_RESOLUTION_2160P,
    "K4A_COLOR_RESOLUTION_3072P": k4a.K4A_COLOR_RESOLUTION_3072P,
    "K4A_DEPTH_MODE_NFOV_2X2BINNED": k4a.K4A_DEPTH_MODE_NFOV_2X2BINNED,
    "K4A_DEPTH_MODE_NFOV_UNBINNED": k4a.K4A_DEPTH_MODE_NFOV_UNBINNED,
    "K4A_DEPTH_MODE_WFOV_UNBINNED": k4a.K4A_DEPTH_MODE_WFOV_UNBINNED,
    "K4A_DEPTH_MODE_WFOV_2X2BINNED": k4a.K4A_DEPTH_MODE_WFOV_2X2BINNED,
    "K4A_DEPTH_MODE_OFF": k4a.K4A_DEPTH_MODE_OFF,
    "K4A_DEPTH_MODE_PASSIVE_IR": k4a.K4A_DEPTH_MODE_PASSIVE_IR,
    "K4A_FRAMES_PER_SECOND_5": k4a.K4A_FRAMES_PER_SECOND_5,
    "K4A_FRAMES_PER_SECOND_15": k4a.K4A_FRAMES_PER_SECOND_15,
    "K4A_FRAMES_PER_SECOND_30": k4a.K4A_FRAMES_PER_SECOND_30,
    "True": True,
    "False": False,
}

# region various constants
OBJECT_DETECTOR_CONFIG_DICT = 'object_detector'
MAX_WORKER_THREADS = 5
